Name:           ros-melodic-rospack
Version:        2.5.4
Release:        1%{?dist}
Summary:        ROS rospack package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/rospack
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       boost-python2-devel
Requires:       boost-python3-devel
Requires:       pkgconfig
Requires:       python-catkin_pkg
Requires:       python-devel
Requires:       python-rosdep
Requires:       ros-melodic-ros-environment
Requires:       tinyxml2-devel
BuildRequires:  boost-devel
BuildRequires:  boost-python2-devel
BuildRequires:  boost-python3-devel
BuildRequires:  gtest-devel
BuildRequires:  pkgconfig
BuildRequires:  python-coverage
BuildRequires:  python-devel
BuildRequires:  ros-melodic-catkin >= 0.5.68
BuildRequires:  ros-melodic-cmake-modules
BuildRequires:  tinyxml2-devel

%description
ROS Package Tool

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Thu Oct 03 2019 Dirk Thomas <dthomas@osrfoundation.org> - 2.5.4-1
- Autogenerated by Bloom

* Mon Mar 04 2019 Dirk Thomas <dthomas@osrfoundation.org> - 2.5.3-0
- Autogenerated by Bloom

* Wed Sep 05 2018 Dirk Thomas <dthomas@osrfoundation.org> - 2.5.2-0
- Autogenerated by Bloom

* Thu May 31 2018 Dirk Thomas <dthomas@osrfoundation.org> - 2.5.1-0
- Autogenerated by Bloom

* Tue Jan 30 2018 Dirk Thomas <dthomas@osrfoundation.org> - 2.5.0-0
- Autogenerated by Bloom

